Spice/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;

namespace Spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        
        public async  Task<IActionResult> Index()
        {
           
           return View(await _db.Category.ToListAsync());
        }

        
        //Get-Create
        public IActionResult Create()
        {
            return View();
        }
       
        //Post-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Add(category);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        //GEt-Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();

            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Update(category);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(category);
            }
        }


        //Get Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category =await _db.Category.FindAsync(id);
            if (category == null)
            {
                return View(category);
            }
            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(int?id)
        {
            if (id==null)
            {
                return NotFound();
            }

            var category = await _db.Category.FindAsync(id);
            _db.Category.Remove(category);
            _db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
    }
}

Spice/Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;

namespace Spice.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CouponController(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Coupon coupon { get; set; }
        public async Task<IActionResult> Index()
        {
            return View(await _db.Coupon.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var files = HttpContext.Request.Form.Files;
            

            if (files.Count() > 0)
            {
                byte[] p1 = null;
                using (var fs1 = files[0].OpenReadStream())
                {
                    using (var ms1 = new MemoryStream())
                    {
                        fs1.CopyTo(ms1);
                        p1 = ms1.ToArray();
                    }
                }
                coupon.Picture = p1;
            }

           

            _db.Coupon.Add(coupon);
            await _db.SaveChangesAsync();

           return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Edit(int ? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var CouponFromDb =await _db.Coupon.SingleOrDefaultAsync(s=> s.Id==id);

            if (CouponFromDb == null)
            {
                return NotFound();
            }
            
            return View(CouponFromDb);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPOST(int?id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (coupon == null)
            {
                return NotFound();
            }
            
            var files = HttpContext.Request.Form.Files;
            var CouponFromDb = await _db.Coupon.SingleOrDefaultAsync(s => s.Id == id);

            if (files.Count() > 0)
            {
               
                /*var imageFromDb = Encoding.Default.GetString(CouponFromDb.Picture);
                if (System.IO.File.Exists(imageFromDb))
                {
                    System.IO.File.Delete(imageFromDb);
                }*/


                byte[] p1 = null;
                using(var fs1 = files[0].OpenReadStream())
                {
                    using(var ms1 = new MemoryStream())
                    {
                        fs1.CopyTo(ms1);
                        p1 = ms1.ToArray();
                    }
                }

                coupon.Picture = p1;
               
            }

            CouponFromDb.Name = coupon.Name;
            CouponFromDb.CouponType = coupon.CouponType;
            CouponFromDb.Discount = coupon.Discount;
            CouponFromDb.MinimumAmount = coupon.MinimumAmount;
            CouponFromDb.IsActive = coupon.IsActive;
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task <IActionResult> Details(int ? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var CouponFromDb = await _db.Coupon.SingleOrDefaultAsync(s => s.Id == id);
            if (CouponFromDb == null)
            {
                return NotFound();
            }

            return View(CouponFromDb);
        }
    }
}

Spice/Areas/Admin/Controllers/MenuItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models.ViewModel;
using Spice.Utility;

namespace Spice.Areas.Admin.Controllers
{
   [Area("Admin")]
    public class MenuItemController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnviroment;

        [BindProperty]
        public MenuItemViewModel MenuItemVm { get; set; }

        public MenuItemController(ApplicationDbContext db, IWebHostEnvironment webHostEnviroment)
        {
            _db = db;
            _webHostEnviroment = webHostEnviroment;

            MenuItemVm = new MenuItemViewModel()
            {
                Category = _db.Category,
                MenuItem = new Models.MenuItem()
            };
        }
        public async Task <IActionResult> Index()
        {
            var menuItems = await _db.MenuItem.Include(s => s.Category).Include(s => s.SubCategory).ToListAsync();
            return View(menuItems);
        }

        //Get Create

        public IActionResult Create()
        {
            return View(MenuItemVm);
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            MenuItemVm.MenuItem.SubCategoryId = Convert.ToInt32(Request.Form["SubCategoryId"].ToString());

            if (!ModelState.IsValid)
            {
                return View(MenuItemVm);
            }

           _db.MenuItem.Add(MenuItemVm.MenuItem);
            await _db.SaveChangesAsync();

            // working on the image saving section

            var webRootPath = _webHostEnviroment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var MenuItemFromDb = await _db.MenuItem.FindAsync(MenuItemVm.MenuItem.Id);

            if (files.Count() > 0)
            {
                //file has been uploaded

                var uploads = Path.Combine(webRootPath, "images");
                var extension = Path.GetExtension(files[0].FileName);

                using (var filesStream = new FileStream(Path.Combine(uploads, MenuItemVm.MenuItem.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(filesStream);

                    MenuItemFromDb.Image = @"\images\" + MenuItemVm.MenuItem.Id + extension;

                }
            }

            else
            {
                // no file was uploaded, so use the default image

                var uploads = Path.Combine(webRootPath, @"images\" + SD.DefaultFoodImage);
                System.IO.File.Copy(uploads, webRootPath + @"\images\" + MenuItemVm.MenuItem.Id + ".png");
                MenuItemFromDb.Image= @"\images\"+ MenuItemVm.MenuItem.Id+".png";
            }

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));


        }

        public async Task<IActionResult> Edit(int ? id)
        {
            if (id == null)
            {
           
                return NotFound();

            }

            MenuItemVm.MenuItem = await _db.MenuItem.Include(s => s.Category).Include(s => s.SubCategory).SingleOrDefaultAsync(s => s.Id == id);
            MenuItemVm.SubCategory = await _db.SubCategory.Where(s => s.CategoryId == MenuItemVm.MenuItem.CategoryId).ToListAsync();

            if (MenuItemVm.MenuItem == null)
            {
                return NotFound();
            }

            return View(MenuItemVm);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPOST(int ? id)
        {
            MenuItemVm.MenuItem.SubCategoryId = Convert.ToInt32(Request.Form["SubCategoryId"].ToString());

            if (!ModelState.IsValid)
            {
                MenuItemVm.SubCategory = await _db.SubCategory.Where(s => s.CategoryId == MenuItemVm.MenuItem.CategoryId).ToListAsync();
                return View(MenuItemVm);
            }

            // working on the image saving section

            var webRootPath = _webHostEnviroment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var MenuItemFromDb = await _db.MenuItem.FindAsync(MenuItemVm.MenuItem.Id);

            

            if (files.Count() > 0)
            {
                //file has been uploaded

                var uploads = Path.Combine(webRootPath, "images");
                var extension_new = Path.GetExtension(files[0].FileName);

                //Delete the original file

                var imagePath = Path.Combine(webRootPath, MenuItemFromDb.Image.TrimStart('\\'));

                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }

                using (var filesStream = new FileStream(Path.Combine(uploads, MenuItemVm.MenuItem.Id + extension_new), FileMode.Create))
                {
                    files[0].CopyTo(filesStream);

                    MenuItemFromDb.Image = @"\images\" + MenuItemVm.MenuItem.Id + extension_new;

                }

                
            }

            MenuItemFromDb.Name = MenuItemVm.MenuItem.Name;
            MenuItemFromDb.Description = MenuItemVm.MenuItem.Description;
            MenuItemFromDb.Price = MenuItemVm.MenuItem.Price;
            MenuItemFromDb.Category = MenuItemVm.MenuItem.Category;
            MenuItemFromDb.SubCategory = MenuItemVm.MenuItem.SubCategory;
            MenuItemFromDb.Spicyness = MenuItemVm.MenuItem.Spicyness;

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));


        }

        public async Task <IActionResult> Details(int ?id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var MenuItemFromDb = await _db.MenuItem.Include(s => s.Category).Include(s => s.SubCategory).SingleOrDefaultAsync(s => s.Id == id);

            if (MenuItemFromDb == null)
            {
                return NotFound();
            }

            return View(MenuItemFromDb);
        }

        public async Task<IActionResult> Delete(int?id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var MenuItemFromDb = await _db.MenuItem.Include(s => s.Category).Include(s => s.SubCategory).SingleOrDefaultAsync(s => s.Id == id);

            if (MenuItemFromDb == null)
            {
                return NotFound();
            }

            return View(MenuItemFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePOST(int ? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var MenuItemFromDb = await _db.MenuItem.Include(s => s.Category).Include(s => s.SubCategory).SingleOrDefaultAsync(s => s.Id == id);

            if (MenuItemFromDb == null)
            {
                return NotFound();
            }

            _db.MenuItem.Remove(MenuItemFromDb);

            // Removing The Image from the server

            var webRootPath = _webHostEnviroment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            if (files.Count() > 0)
            {
                var imagePath = Path.Combine(webRootPath, MenuItemFromDb.Image.TrimStart('\\'));

                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
            }

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Spice/Views/Shared/_CreateAndBackTolistButton.cshtml
    <div class="col-6">
        <input type="submit" value="Create" class="btn btn-info form-control" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back to list</a>
    </div>

Spice/Views/Shared/_CreateButtonPartial.cshtml
<a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i>  Create New</a>

Spice/Views/Shared/_DeleteAndBackToListButton.cshtml
<div class="form-group row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" value="Delete" />
    </div>
    <div class="col-6">
        <a asp-action="index" class="btn btn-info form-control">Back To List</a>
    </div>
</div>

Spice/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int
    <div class="form-group row">
        <div class="col-6">
            <a asp-action="Edit" asp-route-id="@Model" class="btn btn-info form-control">
                Edit
            </a>
        </div>
        <div class="col-6">
            <a asp-action="index" class="btn btn-success form-control">
                Back To List
            </a>
        </div>
    </div>

Spice/Views/Shared/_EditAndBackToListButton.cshtml
<div  class="form-group row" >
  <div class="col-6">
          <input type="submit" value="Update" class="btn btn-success form-control" />
  </div>
  <div class="col-6">
           <a asp-action="index"  class="btn btn-info form-control">Back To List</a>
  </div>
</div>

Spice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Spice</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item dropdown text-white-50">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub Category</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">MenuItem</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">Coupons</a>
                                <a class="dropdown-item">Users</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white-50" style="background-color:#343a40">
        <div class="container">
            &copy; 2021 - Spice
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/e8ee8a98a0.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Spice/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Spice/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-primary">
            <i class="fas fa-edit"></i>
        </a>
        <a asp-action="Details" asp-route-id="@Model" class="btn btn-success">
            <i class="fas fa-list-alt"></i>
        </a>
        <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

Spice/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MenuItem>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ", string.Empty) menu-restaurant">
        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
        </div>

        @foreach(var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin:10px 0px; padding:10px;">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image" style="width:99%; border-radius: 5px; border:1px solid #bbb9b4" />
                    </div>

                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:21px; color:maroon">@item.Name</label>
                                @if (item.Spicyness == "1")
                                {

                                }
                                @if (item.Spicyness == "2")
                                {

                                }
                                @if (item.Spicyness == "3")
                                {

                                }
                            </div>
                            <div class="col-4 text-right" style="color:maroon">
                                <h4>#@item.Price</h4>
                            </div>
                        </div>

                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@item.Description</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">

                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary form-control">Details</a>

                        </div>
                    </div>
                </div>

            </div>
        }

        <div class="p-4"></div>
    </div>
}